### ISSUE TITLE
Can I use Li.Fi or SDK/API to receive and transfer fund cross chains?

### ISSUE THREAD

**Issue by zydjohnHotmail** [lifinance/sdk-node-sample#7]
Hello:
I am new to Li.Fi, I think it is very promising.  But I want to know one specific thing: can I receive one token RUFF (Ruff Chain) from HECO (Huobi) network, and after paying gas fees, send all the rest to another address in Ethereum (ERC20) network?
I have installed Exodus wallet on Windows 10 PC, and I added Ruff as recognized token in the Exodus wallet.
But I have no idea if I can do this via Li.Fi web interface first?
Please advise on if it is possible via web interface.
If yes, then let me know if it is can be done via SDK, I have experience with Node.js (version 19.2.0), do you have npm package for this or not.
Also provide a general idea on how to do this, if possible, via SDK.
For example, do I have to provide the token's contract address, or HECO RPC url, or anything necessary information, like receiver and sender address and gas fees?
Thanks,

**Comment by maxklenk** [comment]
We don't support HECO chain, so that swap will not work.
It is best to try an interface such as https://jumper.exchange/ that uses the LI.FI API to see what routes are possible.
